[phases.setup]
nixPkgs = ["python3", "python3-pip", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python app.py"
